// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: ctx, userID, code
func (_m *AuthServiceMock) Activate(ctx context.Context, userID string, code string) (string, error) {
	ret := _m.Called(ctx, userID, code)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthServiceMock_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type AuthServiceMock_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - code string
func (_e *AuthServiceMock_Expecter) Activate(ctx interface{}, userID interface{}, code interface{}) *AuthServiceMock_Activate_Call {
	return &AuthServiceMock_Activate_Call{Call: _e.mock.On("Activate", ctx, userID, code)}
}

func (_c *AuthServiceMock_Activate_Call) Run(run func(ctx context.Context, userID string, code string)) *AuthServiceMock_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthServiceMock_Activate_Call) Return(sessionID string, err error) *AuthServiceMock_Activate_Call {
	_c.Call.Return(sessionID, err)
	return _c
}

func (_c *AuthServiceMock_Activate_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *AuthServiceMock_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyCode provides a mock function with given fields: ctx, email, code
func (_m *AuthServiceMock) ApplyCode(ctx context.Context, email string, code string) (string, error) {
	ret := _m.Called(ctx, email, code)

	if len(ret) == 0 {
		panic("no return value specified for ApplyCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthServiceMock_ApplyCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyCode'
type AuthServiceMock_ApplyCode_Call struct {
	*mock.Call
}

// ApplyCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
func (_e *AuthServiceMock_Expecter) ApplyCode(ctx interface{}, email interface{}, code interface{}) *AuthServiceMock_ApplyCode_Call {
	return &AuthServiceMock_ApplyCode_Call{Call: _e.mock.On("ApplyCode", ctx, email, code)}
}

func (_c *AuthServiceMock_ApplyCode_Call) Run(run func(ctx context.Context, email string, code string)) *AuthServiceMock_ApplyCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthServiceMock_ApplyCode_Call) Return(sessionID string, err error) *AuthServiceMock_ApplyCode_Call {
	_c.Call.Return(sessionID, err)
	return _c
}

func (_c *AuthServiceMock_ApplyCode_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *AuthServiceMock_ApplyCode_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email
func (_m *AuthServiceMock) Login(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthServiceMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthServiceMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AuthServiceMock_Expecter) Login(ctx interface{}, email interface{}) *AuthServiceMock_Login_Call {
	return &AuthServiceMock_Login_Call{Call: _e.mock.On("Login", ctx, email)}
}

func (_c *AuthServiceMock_Login_Call) Run(run func(ctx context.Context, email string)) *AuthServiceMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthServiceMock_Login_Call) Return(_a0 error) *AuthServiceMock_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthServiceMock_Login_Call) RunAndReturn(run func(context.Context, string) error) *AuthServiceMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, ip, email
func (_m *AuthServiceMock) Register(ctx context.Context, ip string, email string) error {
	ret := _m.Called(ctx, ip, email)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, ip, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthServiceMock_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthServiceMock_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - email string
func (_e *AuthServiceMock_Expecter) Register(ctx interface{}, ip interface{}, email interface{}) *AuthServiceMock_Register_Call {
	return &AuthServiceMock_Register_Call{Call: _e.mock.On("Register", ctx, ip, email)}
}

func (_c *AuthServiceMock_Register_Call) Run(run func(ctx context.Context, ip string, email string)) *AuthServiceMock_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthServiceMock_Register_Call) Return(_a0 error) *AuthServiceMock_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthServiceMock_Register_Call) RunAndReturn(run func(context.Context, string, string) error) *AuthServiceMock_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
