// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ClientRepositoryMock is an autogenerated mock type for the ClientRepository type
type ClientRepositoryMock struct {
	mock.Mock
}

type ClientRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientRepositoryMock) EXPECT() *ClientRepositoryMock_Expecter {
	return &ClientRepositoryMock_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx, userID
func (_m *ClientRepositoryMock) FindAll(ctx context.Context, userID string) ([]domain.Client, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Client, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Client); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRepositoryMock_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type ClientRepositoryMock_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ClientRepositoryMock_Expecter) FindAll(ctx interface{}, userID interface{}) *ClientRepositoryMock_FindAll_Call {
	return &ClientRepositoryMock_FindAll_Call{Call: _e.mock.On("FindAll", ctx, userID)}
}

func (_c *ClientRepositoryMock_FindAll_Call) Run(run func(ctx context.Context, userID string)) *ClientRepositoryMock_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientRepositoryMock_FindAll_Call) Return(_a0 []domain.Client, _a1 error) *ClientRepositoryMock_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientRepositoryMock_FindAll_Call) RunAndReturn(run func(context.Context, string) ([]domain.Client, error)) *ClientRepositoryMock_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID, id
func (_m *ClientRepositoryMock) FindByID(ctx context.Context, userID string, id string) (domain.Client, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Client, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Client); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ClientRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ClientRepositoryMock_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *ClientRepositoryMock_FindByID_Call {
	return &ClientRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *ClientRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, userID string, id string)) *ClientRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRepositoryMock_FindByID_Call) Return(_a0 domain.Client, _a1 error) *ClientRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (domain.Client, error)) *ClientRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientRepositoryMock creates a new instance of ClientRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientRepositoryMock {
	mock := &ClientRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
