// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ClientServiceMock is an autogenerated mock type for the ClientService type
type ClientServiceMock struct {
	mock.Mock
}

type ClientServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientServiceMock) EXPECT() *ClientServiceMock_Expecter {
	return &ClientServiceMock_Expecter{mock: &_m.Mock}
}

// Archive provides a mock function with given fields: ctx, userID, clientID
func (_m *ClientServiceMock) Archive(ctx context.Context, userID string, clientID string) (domain.Client, error) {
	ret := _m.Called(ctx, userID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Archive")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Client, error)); ok {
		return rf(ctx, userID, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Client); ok {
		r0 = rf(ctx, userID, clientID)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientServiceMock_Archive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Archive'
type ClientServiceMock_Archive_Call struct {
	*mock.Call
}

// Archive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clientID string
func (_e *ClientServiceMock_Expecter) Archive(ctx interface{}, userID interface{}, clientID interface{}) *ClientServiceMock_Archive_Call {
	return &ClientServiceMock_Archive_Call{Call: _e.mock.On("Archive", ctx, userID, clientID)}
}

func (_c *ClientServiceMock_Archive_Call) Run(run func(ctx context.Context, userID string, clientID string)) *ClientServiceMock_Archive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientServiceMock_Archive_Call) Return(_a0 domain.Client, _a1 error) *ClientServiceMock_Archive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientServiceMock_Archive_Call) RunAndReturn(run func(context.Context, string, string) (domain.Client, error)) *ClientServiceMock_Archive_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, client
func (_m *ClientServiceMock) Create(ctx context.Context, client domain.Client) (domain.Client, error) {
	ret := _m.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Client) (domain.Client, error)); ok {
		return rf(ctx, client)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Client) domain.Client); ok {
		r0 = rf(ctx, client)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Client) error); ok {
		r1 = rf(ctx, client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ClientServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - client domain.Client
func (_e *ClientServiceMock_Expecter) Create(ctx interface{}, client interface{}) *ClientServiceMock_Create_Call {
	return &ClientServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, client)}
}

func (_c *ClientServiceMock_Create_Call) Run(run func(ctx context.Context, client domain.Client)) *ClientServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Client))
	})
	return _c
}

func (_c *ClientServiceMock_Create_Call) Return(_a0 domain.Client, _a1 error) *ClientServiceMock_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientServiceMock_Create_Call) RunAndReturn(run func(context.Context, domain.Client) (domain.Client, error)) *ClientServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Unarchive provides a mock function with given fields: ctx, userID, clientID
func (_m *ClientServiceMock) Unarchive(ctx context.Context, userID string, clientID string) (domain.Client, error) {
	ret := _m.Called(ctx, userID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Unarchive")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Client, error)); ok {
		return rf(ctx, userID, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Client); ok {
		r0 = rf(ctx, userID, clientID)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientServiceMock_Unarchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unarchive'
type ClientServiceMock_Unarchive_Call struct {
	*mock.Call
}

// Unarchive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clientID string
func (_e *ClientServiceMock_Expecter) Unarchive(ctx interface{}, userID interface{}, clientID interface{}) *ClientServiceMock_Unarchive_Call {
	return &ClientServiceMock_Unarchive_Call{Call: _e.mock.On("Unarchive", ctx, userID, clientID)}
}

func (_c *ClientServiceMock_Unarchive_Call) Run(run func(ctx context.Context, userID string, clientID string)) *ClientServiceMock_Unarchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientServiceMock_Unarchive_Call) Return(_a0 domain.Client, _a1 error) *ClientServiceMock_Unarchive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientServiceMock_Unarchive_Call) RunAndReturn(run func(context.Context, string, string) (domain.Client, error)) *ClientServiceMock_Unarchive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, client
func (_m *ClientServiceMock) Update(ctx context.Context, client domain.Client) (domain.Client, error) {
	ret := _m.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Client) (domain.Client, error)); ok {
		return rf(ctx, client)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Client) domain.Client); ok {
		r0 = rf(ctx, client)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Client) error); ok {
		r1 = rf(ctx, client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ClientServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - client domain.Client
func (_e *ClientServiceMock_Expecter) Update(ctx interface{}, client interface{}) *ClientServiceMock_Update_Call {
	return &ClientServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, client)}
}

func (_c *ClientServiceMock_Update_Call) Run(run func(ctx context.Context, client domain.Client)) *ClientServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Client))
	})
	return _c
}

func (_c *ClientServiceMock_Update_Call) Return(_a0 domain.Client, _a1 error) *ClientServiceMock_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientServiceMock_Update_Call) RunAndReturn(run func(context.Context, domain.Client) (domain.Client, error)) *ClientServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientServiceMock creates a new instance of ClientServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientServiceMock {
	mock := &ClientServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
