// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// CookieManagerMock is an autogenerated mock type for the CookieManager type
type CookieManagerMock struct {
	mock.Mock
}

type CookieManagerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CookieManagerMock) EXPECT() *CookieManagerMock_Expecter {
	return &CookieManagerMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: c, v
func (_m *CookieManagerMock) Create(c *fiber.Ctx, v string) {
	_m.Called(c, v)
}

// CookieManagerMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CookieManagerMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - v string
func (_e *CookieManagerMock_Expecter) Create(c interface{}, v interface{}) *CookieManagerMock_Create_Call {
	return &CookieManagerMock_Create_Call{Call: _e.mock.On("Create", c, v)}
}

func (_c *CookieManagerMock_Create_Call) Run(run func(c *fiber.Ctx, v string)) *CookieManagerMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx), args[1].(string))
	})
	return _c
}

func (_c *CookieManagerMock_Create_Call) Return() *CookieManagerMock_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *CookieManagerMock_Create_Call) RunAndReturn(run func(*fiber.Ctx, string)) *CookieManagerMock_Create_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: c
func (_m *CookieManagerMock) Get(c *fiber.Ctx) string {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CookieManagerMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CookieManagerMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *CookieManagerMock_Expecter) Get(c interface{}) *CookieManagerMock_Get_Call {
	return &CookieManagerMock_Get_Call{Call: _e.mock.On("Get", c)}
}

func (_c *CookieManagerMock_Get_Call) Run(run func(c *fiber.Ctx)) *CookieManagerMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *CookieManagerMock_Get_Call) Return(_a0 string) *CookieManagerMock_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CookieManagerMock_Get_Call) RunAndReturn(run func(*fiber.Ctx) string) *CookieManagerMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiresDays provides a mock function with no fields
func (_m *CookieManagerMock) GetExpiresDays() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExpiresDays")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// CookieManagerMock_GetExpiresDays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiresDays'
type CookieManagerMock_GetExpiresDays_Call struct {
	*mock.Call
}

// GetExpiresDays is a helper method to define mock.On call
func (_e *CookieManagerMock_Expecter) GetExpiresDays() *CookieManagerMock_GetExpiresDays_Call {
	return &CookieManagerMock_GetExpiresDays_Call{Call: _e.mock.On("GetExpiresDays")}
}

func (_c *CookieManagerMock_GetExpiresDays_Call) Run(run func()) *CookieManagerMock_GetExpiresDays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CookieManagerMock_GetExpiresDays_Call) Return(_a0 int) *CookieManagerMock_GetExpiresDays_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CookieManagerMock_GetExpiresDays_Call) RunAndReturn(run func() int) *CookieManagerMock_GetExpiresDays_Call {
	_c.Call.Return(run)
	return _c
}

// NewCookieManagerMock creates a new instance of CookieManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCookieManagerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CookieManagerMock {
	mock := &CookieManagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
