// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FavoriteRepositoryMock is an autogenerated mock type for the FavoriteRepository type
type FavoriteRepositoryMock struct {
	mock.Mock
}

type FavoriteRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FavoriteRepositoryMock) EXPECT() *FavoriteRepositoryMock_Expecter {
	return &FavoriteRepositoryMock_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx, userID
func (_m *FavoriteRepositoryMock) FindAll(ctx context.Context, userID string) ([]domain.Favorite, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Favorite, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Favorite); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Favorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavoriteRepositoryMock_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type FavoriteRepositoryMock_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *FavoriteRepositoryMock_Expecter) FindAll(ctx interface{}, userID interface{}) *FavoriteRepositoryMock_FindAll_Call {
	return &FavoriteRepositoryMock_FindAll_Call{Call: _e.mock.On("FindAll", ctx, userID)}
}

func (_c *FavoriteRepositoryMock_FindAll_Call) Run(run func(ctx context.Context, userID string)) *FavoriteRepositoryMock_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FavoriteRepositoryMock_FindAll_Call) Return(_a0 []domain.Favorite, _a1 error) *FavoriteRepositoryMock_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FavoriteRepositoryMock_FindAll_Call) RunAndReturn(run func(context.Context, string) ([]domain.Favorite, error)) *FavoriteRepositoryMock_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID, id
func (_m *FavoriteRepositoryMock) FindByID(ctx context.Context, userID string, id string) (domain.Favorite, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Favorite, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Favorite); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Favorite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavoriteRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type FavoriteRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *FavoriteRepositoryMock_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *FavoriteRepositoryMock_FindByID_Call {
	return &FavoriteRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *FavoriteRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, userID string, id string)) *FavoriteRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *FavoriteRepositoryMock_FindByID_Call) Return(_a0 domain.Favorite, _a1 error) *FavoriteRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FavoriteRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (domain.Favorite, error)) *FavoriteRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewFavoriteRepositoryMock creates a new instance of FavoriteRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavoriteRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavoriteRepositoryMock {
	mock := &FavoriteRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
