// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FavoriteServiceMock is an autogenerated mock type for the FavoriteService type
type FavoriteServiceMock struct {
	mock.Mock
}

type FavoriteServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FavoriteServiceMock) EXPECT() *FavoriteServiceMock_Expecter {
	return &FavoriteServiceMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, favorite
func (_m *FavoriteServiceMock) Create(ctx context.Context, favorite domain.Favorite) (domain.Favorite, error) {
	ret := _m.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Favorite) (domain.Favorite, error)); ok {
		return rf(ctx, favorite)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Favorite) domain.Favorite); ok {
		r0 = rf(ctx, favorite)
	} else {
		r0 = ret.Get(0).(domain.Favorite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Favorite) error); ok {
		r1 = rf(ctx, favorite)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavoriteServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FavoriteServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite domain.Favorite
func (_e *FavoriteServiceMock_Expecter) Create(ctx interface{}, favorite interface{}) *FavoriteServiceMock_Create_Call {
	return &FavoriteServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, favorite)}
}

func (_c *FavoriteServiceMock_Create_Call) Run(run func(ctx context.Context, favorite domain.Favorite)) *FavoriteServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Favorite))
	})
	return _c
}

func (_c *FavoriteServiceMock_Create_Call) Return(_a0 domain.Favorite, _a1 error) *FavoriteServiceMock_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FavoriteServiceMock_Create_Call) RunAndReturn(run func(context.Context, domain.Favorite) (domain.Favorite, error)) *FavoriteServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *FavoriteServiceMock) Delete(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoriteServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FavoriteServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *FavoriteServiceMock_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *FavoriteServiceMock_Delete_Call {
	return &FavoriteServiceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *FavoriteServiceMock_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *FavoriteServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *FavoriteServiceMock_Delete_Call) Return(_a0 error) *FavoriteServiceMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoriteServiceMock_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *FavoriteServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, favorite
func (_m *FavoriteServiceMock) Update(ctx context.Context, favorite domain.Favorite) (domain.Favorite, error) {
	ret := _m.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Favorite) (domain.Favorite, error)); ok {
		return rf(ctx, favorite)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Favorite) domain.Favorite); ok {
		r0 = rf(ctx, favorite)
	} else {
		r0 = ret.Get(0).(domain.Favorite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Favorite) error); ok {
		r1 = rf(ctx, favorite)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavoriteServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type FavoriteServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite domain.Favorite
func (_e *FavoriteServiceMock_Expecter) Update(ctx interface{}, favorite interface{}) *FavoriteServiceMock_Update_Call {
	return &FavoriteServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, favorite)}
}

func (_c *FavoriteServiceMock_Update_Call) Run(run func(ctx context.Context, favorite domain.Favorite)) *FavoriteServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Favorite))
	})
	return _c
}

func (_c *FavoriteServiceMock_Update_Call) Return(_a0 domain.Favorite, _a1 error) *FavoriteServiceMock_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FavoriteServiceMock_Update_Call) RunAndReturn(run func(context.Context, domain.Favorite) (domain.Favorite, error)) *FavoriteServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewFavoriteServiceMock creates a new instance of FavoriteServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavoriteServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavoriteServiceMock {
	mock := &FavoriteServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
