// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ProjectServiceMock is an autogenerated mock type for the ProjectService type
type ProjectServiceMock struct {
	mock.Mock
}

type ProjectServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectServiceMock) EXPECT() *ProjectServiceMock_Expecter {
	return &ProjectServiceMock_Expecter{mock: &_m.Mock}
}

// Archive provides a mock function with given fields: ctx, userID, projectID
func (_m *ProjectServiceMock) Archive(ctx context.Context, userID string, projectID string) (domain.Project, error) {
	ret := _m.Called(ctx, userID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for Archive")
	}

	var r0 domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Project, error)); ok {
		return rf(ctx, userID, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Project); ok {
		r0 = rf(ctx, userID, projectID)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProjectServiceMock_Archive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Archive'
type ProjectServiceMock_Archive_Call struct {
	*mock.Call
}

// Archive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - projectID string
func (_e *ProjectServiceMock_Expecter) Archive(ctx interface{}, userID interface{}, projectID interface{}) *ProjectServiceMock_Archive_Call {
	return &ProjectServiceMock_Archive_Call{Call: _e.mock.On("Archive", ctx, userID, projectID)}
}

func (_c *ProjectServiceMock_Archive_Call) Run(run func(ctx context.Context, userID string, projectID string)) *ProjectServiceMock_Archive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProjectServiceMock_Archive_Call) Return(_a0 domain.Project, _a1 error) *ProjectServiceMock_Archive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProjectServiceMock_Archive_Call) RunAndReturn(run func(context.Context, string, string) (domain.Project, error)) *ProjectServiceMock_Archive_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, project
func (_m *ProjectServiceMock) Create(ctx context.Context, project domain.Project) (domain.Project, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Project) (domain.Project, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Project) domain.Project); ok {
		r0 = rf(ctx, project)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Project) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProjectServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProjectServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - project domain.Project
func (_e *ProjectServiceMock_Expecter) Create(ctx interface{}, project interface{}) *ProjectServiceMock_Create_Call {
	return &ProjectServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, project)}
}

func (_c *ProjectServiceMock_Create_Call) Run(run func(ctx context.Context, project domain.Project)) *ProjectServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Project))
	})
	return _c
}

func (_c *ProjectServiceMock_Create_Call) Return(_a0 domain.Project, _a1 error) *ProjectServiceMock_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProjectServiceMock_Create_Call) RunAndReturn(run func(context.Context, domain.Project) (domain.Project, error)) *ProjectServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Unarchive provides a mock function with given fields: ctx, userID, projectID
func (_m *ProjectServiceMock) Unarchive(ctx context.Context, userID string, projectID string) (domain.Project, error) {
	ret := _m.Called(ctx, userID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for Unarchive")
	}

	var r0 domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Project, error)); ok {
		return rf(ctx, userID, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Project); ok {
		r0 = rf(ctx, userID, projectID)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProjectServiceMock_Unarchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unarchive'
type ProjectServiceMock_Unarchive_Call struct {
	*mock.Call
}

// Unarchive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - projectID string
func (_e *ProjectServiceMock_Expecter) Unarchive(ctx interface{}, userID interface{}, projectID interface{}) *ProjectServiceMock_Unarchive_Call {
	return &ProjectServiceMock_Unarchive_Call{Call: _e.mock.On("Unarchive", ctx, userID, projectID)}
}

func (_c *ProjectServiceMock_Unarchive_Call) Run(run func(ctx context.Context, userID string, projectID string)) *ProjectServiceMock_Unarchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProjectServiceMock_Unarchive_Call) Return(_a0 domain.Project, _a1 error) *ProjectServiceMock_Unarchive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProjectServiceMock_Unarchive_Call) RunAndReturn(run func(context.Context, string, string) (domain.Project, error)) *ProjectServiceMock_Unarchive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, project
func (_m *ProjectServiceMock) Update(ctx context.Context, project domain.Project) (domain.Project, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Project) (domain.Project, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Project) domain.Project); ok {
		r0 = rf(ctx, project)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Project) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProjectServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProjectServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - project domain.Project
func (_e *ProjectServiceMock_Expecter) Update(ctx interface{}, project interface{}) *ProjectServiceMock_Update_Call {
	return &ProjectServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, project)}
}

func (_c *ProjectServiceMock_Update_Call) Run(run func(ctx context.Context, project domain.Project)) *ProjectServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Project))
	})
	return _c
}

func (_c *ProjectServiceMock_Update_Call) Return(_a0 domain.Project, _a1 error) *ProjectServiceMock_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProjectServiceMock_Update_Call) RunAndReturn(run func(context.Context, domain.Project) (domain.Project, error)) *ProjectServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewProjectServiceMock creates a new instance of ProjectServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectServiceMock {
	mock := &ProjectServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
