// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SanitizerMock is an autogenerated mock type for the Sanitizer type
type SanitizerMock struct {
	mock.Mock
}

type SanitizerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SanitizerMock) EXPECT() *SanitizerMock_Expecter {
	return &SanitizerMock_Expecter{mock: &_m.Mock}
}

// Sanitize provides a mock function with given fields: input
func (_m *SanitizerMock) Sanitize(input string) string {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Sanitize")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SanitizerMock_Sanitize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sanitize'
type SanitizerMock_Sanitize_Call struct {
	*mock.Call
}

// Sanitize is a helper method to define mock.On call
//   - input string
func (_e *SanitizerMock_Expecter) Sanitize(input interface{}) *SanitizerMock_Sanitize_Call {
	return &SanitizerMock_Sanitize_Call{Call: _e.mock.On("Sanitize", input)}
}

func (_c *SanitizerMock_Sanitize_Call) Run(run func(input string)) *SanitizerMock_Sanitize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SanitizerMock_Sanitize_Call) Return(_a0 string) *SanitizerMock_Sanitize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SanitizerMock_Sanitize_Call) RunAndReturn(run func(string) string) *SanitizerMock_Sanitize_Call {
	_c.Call.Return(run)
	return _c
}

// NewSanitizerMock creates a new instance of SanitizerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSanitizerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SanitizerMock {
	mock := &SanitizerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
