// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SessionRepositoryMock is an autogenerated mock type for the SessionRepository type
type SessionRepositoryMock struct {
	mock.Mock
}

type SessionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepositoryMock) EXPECT() *SessionRepositoryMock_Expecter {
	return &SessionRepositoryMock_Expecter{mock: &_m.Mock}
}

// DeleteByCID provides a mock function with given fields: ctx, cid
func (_m *SessionRepositoryMock) DeleteByCID(ctx context.Context, cid string) error {
	ret := _m.Called(ctx, cid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, cid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepositoryMock_DeleteByCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCID'
type SessionRepositoryMock_DeleteByCID_Call struct {
	*mock.Call
}

// DeleteByCID is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
func (_e *SessionRepositoryMock_Expecter) DeleteByCID(ctx interface{}, cid interface{}) *SessionRepositoryMock_DeleteByCID_Call {
	return &SessionRepositoryMock_DeleteByCID_Call{Call: _e.mock.On("DeleteByCID", ctx, cid)}
}

func (_c *SessionRepositoryMock_DeleteByCID_Call) Run(run func(ctx context.Context, cid string)) *SessionRepositoryMock_DeleteByCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionRepositoryMock_DeleteByCID_Call) Return(_a0 error) *SessionRepositoryMock_DeleteByCID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepositoryMock_DeleteByCID_Call) RunAndReturn(run func(context.Context, string) error) *SessionRepositoryMock_DeleteByCID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCID provides a mock function with given fields: ctx, cid
func (_m *SessionRepositoryMock) FindByCID(ctx context.Context, cid string) (domain.Session, error) {
	ret := _m.Called(ctx, cid)

	if len(ret) == 0 {
		panic("no return value specified for FindByCID")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Session, error)); ok {
		return rf(ctx, cid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Session); ok {
		r0 = rf(ctx, cid)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepositoryMock_FindByCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCID'
type SessionRepositoryMock_FindByCID_Call struct {
	*mock.Call
}

// FindByCID is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
func (_e *SessionRepositoryMock_Expecter) FindByCID(ctx interface{}, cid interface{}) *SessionRepositoryMock_FindByCID_Call {
	return &SessionRepositoryMock_FindByCID_Call{Call: _e.mock.On("FindByCID", ctx, cid)}
}

func (_c *SessionRepositoryMock_FindByCID_Call) Run(run func(ctx context.Context, cid string)) *SessionRepositoryMock_FindByCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionRepositoryMock_FindByCID_Call) Return(_a0 domain.Session, _a1 error) *SessionRepositoryMock_FindByCID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepositoryMock_FindByCID_Call) RunAndReturn(run func(context.Context, string) (domain.Session, error)) *SessionRepositoryMock_FindByCID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID, id
func (_m *SessionRepositoryMock) FindByID(ctx context.Context, userID string, id string) (domain.Session, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Session, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Session); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type SessionRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *SessionRepositoryMock_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *SessionRepositoryMock_FindByID_Call {
	return &SessionRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *SessionRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, userID string, id string)) *SessionRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SessionRepositoryMock_FindByID_Call) Return(_a0 domain.Session, _a1 error) *SessionRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (domain.Session, error)) *SessionRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepositoryMock creates a new instance of SessionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepositoryMock {
	mock := &SessionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
