// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionServiceMock is an autogenerated mock type for the SessionService type
type SessionServiceMock struct {
	mock.Mock
}

type SessionServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionServiceMock) EXPECT() *SessionServiceMock_Expecter {
	return &SessionServiceMock_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, userID, outdatedTime
func (_m *SessionServiceMock) List(ctx context.Context, userID string, outdatedTime time.Time) ([]domain.Session, error) {
	ret := _m.Called(ctx, userID, outdatedTime)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]domain.Session, error)); ok {
		return rf(ctx, userID, outdatedTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []domain.Session); ok {
		r0 = rf(ctx, userID, outdatedTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, userID, outdatedTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type SessionServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - outdatedTime time.Time
func (_e *SessionServiceMock_Expecter) List(ctx interface{}, userID interface{}, outdatedTime interface{}) *SessionServiceMock_List_Call {
	return &SessionServiceMock_List_Call{Call: _e.mock.On("List", ctx, userID, outdatedTime)}
}

func (_c *SessionServiceMock_List_Call) Run(run func(ctx context.Context, userID string, outdatedTime time.Time)) *SessionServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *SessionServiceMock_List_Call) Return(_a0 []domain.Session, _a1 error) *SessionServiceMock_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionServiceMock_List_Call) RunAndReturn(run func(context.Context, string, time.Time) ([]domain.Session, error)) *SessionServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionServiceMock creates a new instance of SessionServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionServiceMock {
	mock := &SessionServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
