// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SettingRepositoryMock is an autogenerated mock type for the SettingRepository type
type SettingRepositoryMock struct {
	mock.Mock
}

type SettingRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SettingRepositoryMock) EXPECT() *SettingRepositoryMock_Expecter {
	return &SettingRepositoryMock_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx, userID
func (_m *SettingRepositoryMock) FindAll(ctx context.Context, userID string) ([]domain.Setting, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Setting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Setting, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Setting); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Setting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingRepositoryMock_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type SettingRepositoryMock_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SettingRepositoryMock_Expecter) FindAll(ctx interface{}, userID interface{}) *SettingRepositoryMock_FindAll_Call {
	return &SettingRepositoryMock_FindAll_Call{Call: _e.mock.On("FindAll", ctx, userID)}
}

func (_c *SettingRepositoryMock_FindAll_Call) Run(run func(ctx context.Context, userID string)) *SettingRepositoryMock_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SettingRepositoryMock_FindAll_Call) Return(_a0 []domain.Setting, _a1 error) *SettingRepositoryMock_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingRepositoryMock_FindAll_Call) RunAndReturn(run func(context.Context, string) ([]domain.Setting, error)) *SettingRepositoryMock_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByKey provides a mock function with given fields: ctx, userID, key
func (_m *SettingRepositoryMock) FindByKey(ctx context.Context, userID string, key string) (domain.Setting, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByKey")
	}

	var r0 domain.Setting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Setting, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Setting); ok {
		r0 = rf(ctx, userID, key)
	} else {
		r0 = ret.Get(0).(domain.Setting)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingRepositoryMock_FindByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByKey'
type SettingRepositoryMock_FindByKey_Call struct {
	*mock.Call
}

// FindByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
func (_e *SettingRepositoryMock_Expecter) FindByKey(ctx interface{}, userID interface{}, key interface{}) *SettingRepositoryMock_FindByKey_Call {
	return &SettingRepositoryMock_FindByKey_Call{Call: _e.mock.On("FindByKey", ctx, userID, key)}
}

func (_c *SettingRepositoryMock_FindByKey_Call) Run(run func(ctx context.Context, userID string, key string)) *SettingRepositoryMock_FindByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SettingRepositoryMock_FindByKey_Call) Return(_a0 domain.Setting, _a1 error) *SettingRepositoryMock_FindByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingRepositoryMock_FindByKey_Call) RunAndReturn(run func(context.Context, string, string) (domain.Setting, error)) *SettingRepositoryMock_FindByKey_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOrUpdate provides a mock function with given fields: ctx, setting
func (_m *SettingRepositoryMock) InsertOrUpdate(ctx context.Context, setting domain.Setting) error {
	ret := _m.Called(ctx, setting)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Setting) error); ok {
		r0 = rf(ctx, setting)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SettingRepositoryMock_InsertOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrUpdate'
type SettingRepositoryMock_InsertOrUpdate_Call struct {
	*mock.Call
}

// InsertOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - setting domain.Setting
func (_e *SettingRepositoryMock_Expecter) InsertOrUpdate(ctx interface{}, setting interface{}) *SettingRepositoryMock_InsertOrUpdate_Call {
	return &SettingRepositoryMock_InsertOrUpdate_Call{Call: _e.mock.On("InsertOrUpdate", ctx, setting)}
}

func (_c *SettingRepositoryMock_InsertOrUpdate_Call) Run(run func(ctx context.Context, setting domain.Setting)) *SettingRepositoryMock_InsertOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Setting))
	})
	return _c
}

func (_c *SettingRepositoryMock_InsertOrUpdate_Call) Return(_a0 error) *SettingRepositoryMock_InsertOrUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SettingRepositoryMock_InsertOrUpdate_Call) RunAndReturn(run func(context.Context, domain.Setting) error) *SettingRepositoryMock_InsertOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewSettingRepositoryMock creates a new instance of SettingRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingRepositoryMock {
	mock := &SettingRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
