// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TaskServiceMock is an autogenerated mock type for the TaskService type
type TaskServiceMock struct {
	mock.Mock
}

type TaskServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskServiceMock) EXPECT() *TaskServiceMock_Expecter {
	return &TaskServiceMock_Expecter{mock: &_m.Mock}
}

// Archive provides a mock function with given fields: ctx, userID, taskID
func (_m *TaskServiceMock) Archive(ctx context.Context, userID string, taskID string) (domain.Task, error) {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Archive")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Task, error)); ok {
		return rf(ctx, userID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Task); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_Archive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Archive'
type TaskServiceMock_Archive_Call struct {
	*mock.Call
}

// Archive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskID string
func (_e *TaskServiceMock_Expecter) Archive(ctx interface{}, userID interface{}, taskID interface{}) *TaskServiceMock_Archive_Call {
	return &TaskServiceMock_Archive_Call{Call: _e.mock.On("Archive", ctx, userID, taskID)}
}

func (_c *TaskServiceMock_Archive_Call) Run(run func(ctx context.Context, userID string, taskID string)) *TaskServiceMock_Archive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TaskServiceMock_Archive_Call) Return(_a0 domain.Task, _a1 error) *TaskServiceMock_Archive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_Archive_Call) RunAndReturn(run func(context.Context, string, string) (domain.Task, error)) *TaskServiceMock_Archive_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function with given fields: ctx, userID, taskID
func (_m *TaskServiceMock) Complete(ctx context.Context, userID string, taskID string) (domain.Task, error) {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Task, error)); ok {
		return rf(ctx, userID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Task); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type TaskServiceMock_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskID string
func (_e *TaskServiceMock_Expecter) Complete(ctx interface{}, userID interface{}, taskID interface{}) *TaskServiceMock_Complete_Call {
	return &TaskServiceMock_Complete_Call{Call: _e.mock.On("Complete", ctx, userID, taskID)}
}

func (_c *TaskServiceMock_Complete_Call) Run(run func(ctx context.Context, userID string, taskID string)) *TaskServiceMock_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TaskServiceMock_Complete_Call) Return(_a0 domain.Task, _a1 error) *TaskServiceMock_Complete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_Complete_Call) RunAndReturn(run func(context.Context, string, string) (domain.Task, error)) *TaskServiceMock_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, task
func (_m *TaskServiceMock) Create(ctx context.Context, task domain.Task) (domain.Task, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) (domain.Task, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) domain.Task); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.Task
func (_e *TaskServiceMock_Expecter) Create(ctx interface{}, task interface{}) *TaskServiceMock_Create_Call {
	return &TaskServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *TaskServiceMock_Create_Call) Run(run func(ctx context.Context, task domain.Task)) *TaskServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Task))
	})
	return _c
}

func (_c *TaskServiceMock_Create_Call) Return(_a0 domain.Task, _a1 error) *TaskServiceMock_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_Create_Call) RunAndReturn(run func(context.Context, domain.Task) (domain.Task, error)) *TaskServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Incomplete provides a mock function with given fields: ctx, userID, taskID
func (_m *TaskServiceMock) Incomplete(ctx context.Context, userID string, taskID string) (domain.Task, error) {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Incomplete")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Task, error)); ok {
		return rf(ctx, userID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Task); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_Incomplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Incomplete'
type TaskServiceMock_Incomplete_Call struct {
	*mock.Call
}

// Incomplete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskID string
func (_e *TaskServiceMock_Expecter) Incomplete(ctx interface{}, userID interface{}, taskID interface{}) *TaskServiceMock_Incomplete_Call {
	return &TaskServiceMock_Incomplete_Call{Call: _e.mock.On("Incomplete", ctx, userID, taskID)}
}

func (_c *TaskServiceMock_Incomplete_Call) Run(run func(ctx context.Context, userID string, taskID string)) *TaskServiceMock_Incomplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TaskServiceMock_Incomplete_Call) Return(_a0 domain.Task, _a1 error) *TaskServiceMock_Incomplete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_Incomplete_Call) RunAndReturn(run func(context.Context, string, string) (domain.Task, error)) *TaskServiceMock_Incomplete_Call {
	_c.Call.Return(run)
	return _c
}

// Report provides a mock function with given fields: ctx, userID, taskID
func (_m *TaskServiceMock) Report(ctx context.Context, userID string, taskID string) (domain.TaskReport, error) {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Report")
	}

	var r0 domain.TaskReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.TaskReport, error)); ok {
		return rf(ctx, userID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.TaskReport); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		r0 = ret.Get(0).(domain.TaskReport)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type TaskServiceMock_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskID string
func (_e *TaskServiceMock_Expecter) Report(ctx interface{}, userID interface{}, taskID interface{}) *TaskServiceMock_Report_Call {
	return &TaskServiceMock_Report_Call{Call: _e.mock.On("Report", ctx, userID, taskID)}
}

func (_c *TaskServiceMock_Report_Call) Run(run func(ctx context.Context, userID string, taskID string)) *TaskServiceMock_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TaskServiceMock_Report_Call) Return(_a0 domain.TaskReport, _a1 error) *TaskServiceMock_Report_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_Report_Call) RunAndReturn(run func(context.Context, string, string) (domain.TaskReport, error)) *TaskServiceMock_Report_Call {
	_c.Call.Return(run)
	return _c
}

// Unarchive provides a mock function with given fields: ctx, userID, taskID
func (_m *TaskServiceMock) Unarchive(ctx context.Context, userID string, taskID string) (domain.Task, error) {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Unarchive")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Task, error)); ok {
		return rf(ctx, userID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Task); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_Unarchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unarchive'
type TaskServiceMock_Unarchive_Call struct {
	*mock.Call
}

// Unarchive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskID string
func (_e *TaskServiceMock_Expecter) Unarchive(ctx interface{}, userID interface{}, taskID interface{}) *TaskServiceMock_Unarchive_Call {
	return &TaskServiceMock_Unarchive_Call{Call: _e.mock.On("Unarchive", ctx, userID, taskID)}
}

func (_c *TaskServiceMock_Unarchive_Call) Run(run func(ctx context.Context, userID string, taskID string)) *TaskServiceMock_Unarchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TaskServiceMock_Unarchive_Call) Return(_a0 domain.Task, _a1 error) *TaskServiceMock_Unarchive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_Unarchive_Call) RunAndReturn(run func(context.Context, string, string) (domain.Task, error)) *TaskServiceMock_Unarchive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, task
func (_m *TaskServiceMock) Update(ctx context.Context, task domain.Task) (domain.Task, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) (domain.Task, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) domain.Task); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TaskServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.Task
func (_e *TaskServiceMock_Expecter) Update(ctx interface{}, task interface{}) *TaskServiceMock_Update_Call {
	return &TaskServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *TaskServiceMock_Update_Call) Run(run func(ctx context.Context, task domain.Task)) *TaskServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Task))
	})
	return _c
}

func (_c *TaskServiceMock_Update_Call) Return(_a0 domain.Task, _a1 error) *TaskServiceMock_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_Update_Call) RunAndReturn(run func(context.Context, domain.Task) (domain.Task, error)) *TaskServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskServiceMock creates a new instance of TaskServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskServiceMock {
	mock := &TaskServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
