// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TaskRepositoryMock is an autogenerated mock type for the TaskRepository type
type TaskRepositoryMock struct {
	mock.Mock
}

type TaskRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskRepositoryMock) EXPECT() *TaskRepositoryMock_Expecter {
	return &TaskRepositoryMock_Expecter{mock: &_m.Mock}
}

// FindByFilter provides a mock function with given fields: ctx, userID, filter
func (_m *TaskRepositoryMock) FindByFilter(ctx context.Context, userID string, filter domain.TaskFilter) ([]domain.Task, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindByFilter")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TaskFilter) ([]domain.Task, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TaskFilter) []domain.Task); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.TaskFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepositoryMock_FindByFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFilter'
type TaskRepositoryMock_FindByFilter_Call struct {
	*mock.Call
}

// FindByFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filter domain.TaskFilter
func (_e *TaskRepositoryMock_Expecter) FindByFilter(ctx interface{}, userID interface{}, filter interface{}) *TaskRepositoryMock_FindByFilter_Call {
	return &TaskRepositoryMock_FindByFilter_Call{Call: _e.mock.On("FindByFilter", ctx, userID, filter)}
}

func (_c *TaskRepositoryMock_FindByFilter_Call) Run(run func(ctx context.Context, userID string, filter domain.TaskFilter)) *TaskRepositoryMock_FindByFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.TaskFilter))
	})
	return _c
}

func (_c *TaskRepositoryMock_FindByFilter_Call) Return(_a0 []domain.Task, _a1 error) *TaskRepositoryMock_FindByFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepositoryMock_FindByFilter_Call) RunAndReturn(run func(context.Context, string, domain.TaskFilter) ([]domain.Task, error)) *TaskRepositoryMock_FindByFilter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID, id
func (_m *TaskRepositoryMock) FindByID(ctx context.Context, userID string, id string) (domain.Task, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Task, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Task); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type TaskRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *TaskRepositoryMock_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *TaskRepositoryMock_FindByID_Call {
	return &TaskRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *TaskRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, userID string, id string)) *TaskRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TaskRepositoryMock_FindByID_Call) Return(_a0 domain.Task, _a1 error) *TaskRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (domain.Task, error)) *TaskRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskRepositoryMock creates a new instance of TaskRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepositoryMock {
	mock := &TaskRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
