// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TimelogServiceMock is an autogenerated mock type for the TimelogService type
type TimelogServiceMock struct {
	mock.Mock
}

type TimelogServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TimelogServiceMock) EXPECT() *TimelogServiceMock_Expecter {
	return &TimelogServiceMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, timelog
func (_m *TimelogServiceMock) Create(ctx context.Context, timelog domain.Timelog) (domain.Timelog, error) {
	ret := _m.Called(ctx, timelog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Timelog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Timelog) (domain.Timelog, error)); ok {
		return rf(ctx, timelog)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Timelog) domain.Timelog); ok {
		r0 = rf(ctx, timelog)
	} else {
		r0 = ret.Get(0).(domain.Timelog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Timelog) error); ok {
		r1 = rf(ctx, timelog)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelogServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TimelogServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - timelog domain.Timelog
func (_e *TimelogServiceMock_Expecter) Create(ctx interface{}, timelog interface{}) *TimelogServiceMock_Create_Call {
	return &TimelogServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, timelog)}
}

func (_c *TimelogServiceMock_Create_Call) Run(run func(ctx context.Context, timelog domain.Timelog)) *TimelogServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Timelog))
	})
	return _c
}

func (_c *TimelogServiceMock_Create_Call) Return(_a0 domain.Timelog, _a1 error) *TimelogServiceMock_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelogServiceMock_Create_Call) RunAndReturn(run func(context.Context, domain.Timelog) (domain.Timelog, error)) *TimelogServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *TimelogServiceMock) Delete(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TimelogServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TimelogServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *TimelogServiceMock_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *TimelogServiceMock_Delete_Call {
	return &TimelogServiceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *TimelogServiceMock_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *TimelogServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TimelogServiceMock_Delete_Call) Return(_a0 error) *TimelogServiceMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TimelogServiceMock_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *TimelogServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindLastN provides a mock function with given fields: ctx, userID, n
func (_m *TimelogServiceMock) FindLastN(ctx context.Context, userID string, n int) ([]domain.Timelog, error) {
	ret := _m.Called(ctx, userID, n)

	if len(ret) == 0 {
		panic("no return value specified for FindLastN")
	}

	var r0 []domain.Timelog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.Timelog, error)); ok {
		return rf(ctx, userID, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.Timelog); ok {
		r0 = rf(ctx, userID, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Timelog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelogServiceMock_FindLastN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLastN'
type TimelogServiceMock_FindLastN_Call struct {
	*mock.Call
}

// FindLastN is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - n int
func (_e *TimelogServiceMock_Expecter) FindLastN(ctx interface{}, userID interface{}, n interface{}) *TimelogServiceMock_FindLastN_Call {
	return &TimelogServiceMock_FindLastN_Call{Call: _e.mock.On("FindLastN", ctx, userID, n)}
}

func (_c *TimelogServiceMock_FindLastN_Call) Run(run func(ctx context.Context, userID string, n int)) *TimelogServiceMock_FindLastN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *TimelogServiceMock_FindLastN_Call) Return(_a0 []domain.Timelog, _a1 error) *TimelogServiceMock_FindLastN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelogServiceMock_FindLastN_Call) RunAndReturn(run func(context.Context, string, int) ([]domain.Timelog, error)) *TimelogServiceMock_FindLastN_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx, userID, timelogID, date, timeEnd
func (_m *TimelogServiceMock) Stop(ctx context.Context, userID string, timelogID string, date string, timeEnd string) (domain.Timelog, error) {
	ret := _m.Called(ctx, userID, timelogID, date, timeEnd)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 domain.Timelog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (domain.Timelog, error)); ok {
		return rf(ctx, userID, timelogID, date, timeEnd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) domain.Timelog); ok {
		r0 = rf(ctx, userID, timelogID, date, timeEnd)
	} else {
		r0 = ret.Get(0).(domain.Timelog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, userID, timelogID, date, timeEnd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelogServiceMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type TimelogServiceMock_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - timelogID string
//   - date string
//   - timeEnd string
func (_e *TimelogServiceMock_Expecter) Stop(ctx interface{}, userID interface{}, timelogID interface{}, date interface{}, timeEnd interface{}) *TimelogServiceMock_Stop_Call {
	return &TimelogServiceMock_Stop_Call{Call: _e.mock.On("Stop", ctx, userID, timelogID, date, timeEnd)}
}

func (_c *TimelogServiceMock_Stop_Call) Run(run func(ctx context.Context, userID string, timelogID string, date string, timeEnd string)) *TimelogServiceMock_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *TimelogServiceMock_Stop_Call) Return(_a0 domain.Timelog, _a1 error) *TimelogServiceMock_Stop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelogServiceMock_Stop_Call) RunAndReturn(run func(context.Context, string, string, string, string) (domain.Timelog, error)) *TimelogServiceMock_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, timelog
func (_m *TimelogServiceMock) Update(ctx context.Context, timelog domain.Timelog) (domain.Timelog, error) {
	ret := _m.Called(ctx, timelog)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Timelog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Timelog) (domain.Timelog, error)); ok {
		return rf(ctx, timelog)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Timelog) domain.Timelog); ok {
		r0 = rf(ctx, timelog)
	} else {
		r0 = ret.Get(0).(domain.Timelog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Timelog) error); ok {
		r1 = rf(ctx, timelog)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelogServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TimelogServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - timelog domain.Timelog
func (_e *TimelogServiceMock_Expecter) Update(ctx interface{}, timelog interface{}) *TimelogServiceMock_Update_Call {
	return &TimelogServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, timelog)}
}

func (_c *TimelogServiceMock_Update_Call) Run(run func(ctx context.Context, timelog domain.Timelog)) *TimelogServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Timelog))
	})
	return _c
}

func (_c *TimelogServiceMock_Update_Call) Return(_a0 domain.Timelog, _a1 error) *TimelogServiceMock_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelogServiceMock_Update_Call) RunAndReturn(run func(context.Context, domain.Timelog) (domain.Timelog, error)) *TimelogServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTimelogServiceMock creates a new instance of TimelogServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimelogServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimelogServiceMock {
	mock := &TimelogServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
