// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlite "capuchin/internal/sqlite"
)

// AuditLogRepositoryMock is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepositoryMock struct {
	mock.Mock
}

type AuditLogRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditLogRepositoryMock) EXPECT() *AuditLogRepositoryMock_Expecter {
	return &AuditLogRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, db, auditLog
func (_m *AuditLogRepositoryMock) Create(ctx context.Context, db sqlite.SQLExecutor, auditLog domain.AuditLog) error {
	ret := _m.Called(ctx, db, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.AuditLog) error); ok {
		r0 = rf(ctx, db, auditLog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuditLogRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuditLogRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - auditLog domain.AuditLog
func (_e *AuditLogRepositoryMock_Expecter) Create(ctx interface{}, db interface{}, auditLog interface{}) *AuditLogRepositoryMock_Create_Call {
	return &AuditLogRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, db, auditLog)}
}

func (_c *AuditLogRepositoryMock_Create_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, auditLog domain.AuditLog)) *AuditLogRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.AuditLog))
	})
	return _c
}

func (_c *AuditLogRepositoryMock_Create_Call) Return(_a0 error) *AuditLogRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuditLogRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.AuditLog) error) *AuditLogRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditLogRepositoryMock creates a new instance of AuditLogRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepositoryMock {
	mock := &AuditLogRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
