// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AuthCodeRepositoryMock is an autogenerated mock type for the AuthCodeRepository type
type AuthCodeRepositoryMock struct {
	mock.Mock
}

type AuthCodeRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthCodeRepositoryMock) EXPECT() *AuthCodeRepositoryMock_Expecter {
	return &AuthCodeRepositoryMock_Expecter{mock: &_m.Mock}
}

// CancelOld provides a mock function with given fields: ctx, olderThan
func (_m *AuthCodeRepositoryMock) CancelOld(ctx context.Context, olderThan time.Time) error {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for CancelOld")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthCodeRepositoryMock_CancelOld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOld'
type AuthCodeRepositoryMock_CancelOld_Call struct {
	*mock.Call
}

// CancelOld is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *AuthCodeRepositoryMock_Expecter) CancelOld(ctx interface{}, olderThan interface{}) *AuthCodeRepositoryMock_CancelOld_Call {
	return &AuthCodeRepositoryMock_CancelOld_Call{Call: _e.mock.On("CancelOld", ctx, olderThan)}
}

func (_c *AuthCodeRepositoryMock_CancelOld_Call) Run(run func(ctx context.Context, olderThan time.Time)) *AuthCodeRepositoryMock_CancelOld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *AuthCodeRepositoryMock_CancelOld_Call) Return(_a0 error) *AuthCodeRepositoryMock_CancelOld_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthCodeRepositoryMock_CancelOld_Call) RunAndReturn(run func(context.Context, time.Time) error) *AuthCodeRepositoryMock_CancelOld_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, authCode
func (_m *AuthCodeRepositoryMock) Create(ctx context.Context, authCode domain.AuthCode) error {
	ret := _m.Called(ctx, authCode)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthCode) error); ok {
		r0 = rf(ctx, authCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthCodeRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuthCodeRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - authCode domain.AuthCode
func (_e *AuthCodeRepositoryMock_Expecter) Create(ctx interface{}, authCode interface{}) *AuthCodeRepositoryMock_Create_Call {
	return &AuthCodeRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, authCode)}
}

func (_c *AuthCodeRepositoryMock_Create_Call) Run(run func(ctx context.Context, authCode domain.AuthCode)) *AuthCodeRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AuthCode))
	})
	return _c
}

func (_c *AuthCodeRepositoryMock_Create_Call) Return(_a0 error) *AuthCodeRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthCodeRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, domain.AuthCode) error) *AuthCodeRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AuthCodeRepositoryMock) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthCodeRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AuthCodeRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AuthCodeRepositoryMock_Expecter) Delete(ctx interface{}, id interface{}) *AuthCodeRepositoryMock_Delete_Call {
	return &AuthCodeRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *AuthCodeRepositoryMock_Delete_Call) Run(run func(ctx context.Context, id string)) *AuthCodeRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthCodeRepositoryMock_Delete_Call) Return(_a0 error) *AuthCodeRepositoryMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthCodeRepositoryMock_Delete_Call) RunAndReturn(run func(context.Context, string) error) *AuthCodeRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, email, code
func (_m *AuthCodeRepositoryMock) Find(ctx context.Context, email string, code string) (domain.AuthCode, error) {
	ret := _m.Called(ctx, email, code)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.AuthCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.AuthCode, error)); ok {
		return rf(ctx, email, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.AuthCode); ok {
		r0 = rf(ctx, email, code)
	} else {
		r0 = ret.Get(0).(domain.AuthCode)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthCodeRepositoryMock_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type AuthCodeRepositoryMock_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
func (_e *AuthCodeRepositoryMock_Expecter) Find(ctx interface{}, email interface{}, code interface{}) *AuthCodeRepositoryMock_Find_Call {
	return &AuthCodeRepositoryMock_Find_Call{Call: _e.mock.On("Find", ctx, email, code)}
}

func (_c *AuthCodeRepositoryMock_Find_Call) Run(run func(ctx context.Context, email string, code string)) *AuthCodeRepositoryMock_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthCodeRepositoryMock_Find_Call) Return(_a0 domain.AuthCode, _a1 error) *AuthCodeRepositoryMock_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthCodeRepositoryMock_Find_Call) RunAndReturn(run func(context.Context, string, string) (domain.AuthCode, error)) *AuthCodeRepositoryMock_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthCodeRepositoryMock creates a new instance of AuthCodeRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthCodeRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthCodeRepositoryMock {
	mock := &AuthCodeRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
