// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlite "capuchin/internal/sqlite"
)

// ClientRepositoryMock is an autogenerated mock type for the ClientRepository type
type ClientRepositoryMock struct {
	mock.Mock
}

type ClientRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientRepositoryMock) EXPECT() *ClientRepositoryMock_Expecter {
	return &ClientRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, db, client
func (_m *ClientRepositoryMock) Create(ctx context.Context, db sqlite.SQLExecutor, client domain.Client) error {
	ret := _m.Called(ctx, db, client)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.Client) error); ok {
		r0 = rf(ctx, db, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ClientRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - client domain.Client
func (_e *ClientRepositoryMock_Expecter) Create(ctx interface{}, db interface{}, client interface{}) *ClientRepositoryMock_Create_Call {
	return &ClientRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, db, client)}
}

func (_c *ClientRepositoryMock_Create_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, client domain.Client)) *ClientRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.Client))
	})
	return _c
}

func (_c *ClientRepositoryMock_Create_Call) Return(_a0 error) *ClientRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.Client) error) *ClientRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID, id
func (_m *ClientRepositoryMock) FindByID(ctx context.Context, userID string, id string) (domain.Client, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Client, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Client); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ClientRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ClientRepositoryMock_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *ClientRepositoryMock_FindByID_Call {
	return &ClientRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *ClientRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, userID string, id string)) *ClientRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRepositoryMock_FindByID_Call) Return(_a0 domain.Client, _a1 error) *ClientRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (domain.Client, error)) *ClientRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, db, client
func (_m *ClientRepositoryMock) Update(ctx context.Context, db sqlite.SQLExecutor, client domain.Client) error {
	ret := _m.Called(ctx, db, client)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.Client) error); ok {
		r0 = rf(ctx, db, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ClientRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - client domain.Client
func (_e *ClientRepositoryMock_Expecter) Update(ctx interface{}, db interface{}, client interface{}) *ClientRepositoryMock_Update_Call {
	return &ClientRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, db, client)}
}

func (_c *ClientRepositoryMock_Update_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, client domain.Client)) *ClientRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.Client))
	})
	return _c
}

func (_c *ClientRepositoryMock_Update_Call) Return(_a0 error) *ClientRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.Client) error) *ClientRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientRepositoryMock creates a new instance of ClientRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientRepositoryMock {
	mock := &ClientRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
