// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlite "capuchin/internal/sqlite"
)

// FavoriteRepositoryMock is an autogenerated mock type for the FavoriteRepository type
type FavoriteRepositoryMock struct {
	mock.Mock
}

type FavoriteRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FavoriteRepositoryMock) EXPECT() *FavoriteRepositoryMock_Expecter {
	return &FavoriteRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, db, favorite
func (_m *FavoriteRepositoryMock) Create(ctx context.Context, db sqlite.SQLExecutor, favorite domain.Favorite) error {
	ret := _m.Called(ctx, db, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.Favorite) error); ok {
		r0 = rf(ctx, db, favorite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoriteRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FavoriteRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - favorite domain.Favorite
func (_e *FavoriteRepositoryMock_Expecter) Create(ctx interface{}, db interface{}, favorite interface{}) *FavoriteRepositoryMock_Create_Call {
	return &FavoriteRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, db, favorite)}
}

func (_c *FavoriteRepositoryMock_Create_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, favorite domain.Favorite)) *FavoriteRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.Favorite))
	})
	return _c
}

func (_c *FavoriteRepositoryMock_Create_Call) Return(_a0 error) *FavoriteRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoriteRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.Favorite) error) *FavoriteRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, db, userID, id
func (_m *FavoriteRepositoryMock) Delete(ctx context.Context, db sqlite.SQLExecutor, userID string, id string) error {
	ret := _m.Called(ctx, db, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, string, string) error); ok {
		r0 = rf(ctx, db, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoriteRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FavoriteRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - userID string
//   - id string
func (_e *FavoriteRepositoryMock_Expecter) Delete(ctx interface{}, db interface{}, userID interface{}, id interface{}) *FavoriteRepositoryMock_Delete_Call {
	return &FavoriteRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, db, userID, id)}
}

func (_c *FavoriteRepositoryMock_Delete_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, userID string, id string)) *FavoriteRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *FavoriteRepositoryMock_Delete_Call) Return(_a0 error) *FavoriteRepositoryMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoriteRepositoryMock_Delete_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, string, string) error) *FavoriteRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID, id
func (_m *FavoriteRepositoryMock) FindByID(ctx context.Context, userID string, id string) (domain.Favorite, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Favorite, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Favorite); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Favorite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavoriteRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type FavoriteRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *FavoriteRepositoryMock_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *FavoriteRepositoryMock_FindByID_Call {
	return &FavoriteRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *FavoriteRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, userID string, id string)) *FavoriteRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *FavoriteRepositoryMock_FindByID_Call) Return(_a0 domain.Favorite, _a1 error) *FavoriteRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FavoriteRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (domain.Favorite, error)) *FavoriteRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, db, favorite
func (_m *FavoriteRepositoryMock) Update(ctx context.Context, db sqlite.SQLExecutor, favorite domain.Favorite) error {
	ret := _m.Called(ctx, db, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.Favorite) error); ok {
		r0 = rf(ctx, db, favorite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoriteRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type FavoriteRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - favorite domain.Favorite
func (_e *FavoriteRepositoryMock_Expecter) Update(ctx interface{}, db interface{}, favorite interface{}) *FavoriteRepositoryMock_Update_Call {
	return &FavoriteRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, db, favorite)}
}

func (_c *FavoriteRepositoryMock_Update_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, favorite domain.Favorite)) *FavoriteRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.Favorite))
	})
	return _c
}

func (_c *FavoriteRepositoryMock_Update_Call) Return(_a0 error) *FavoriteRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoriteRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.Favorite) error) *FavoriteRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewFavoriteRepositoryMock creates a new instance of FavoriteRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavoriteRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavoriteRepositoryMock {
	mock := &FavoriteRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
