// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	mailer "capuchin/internal/mailer"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MailServiceMock is an autogenerated mock type for the MailService type
type MailServiceMock struct {
	mock.Mock
}

type MailServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MailServiceMock) EXPECT() *MailServiceMock_Expecter {
	return &MailServiceMock_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, recipients, subject, tpl, content
func (_m *MailServiceMock) Send(ctx context.Context, recipients []string, subject string, tpl mailer.Template, content interface{}) error {
	ret := _m.Called(ctx, recipients, subject, tpl, content)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, mailer.Template, interface{}) error); ok {
		r0 = rf(ctx, recipients, subject, tpl, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MailServiceMock_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MailServiceMock_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - recipients []string
//   - subject string
//   - tpl mailer.Template
//   - content interface{}
func (_e *MailServiceMock_Expecter) Send(ctx interface{}, recipients interface{}, subject interface{}, tpl interface{}, content interface{}) *MailServiceMock_Send_Call {
	return &MailServiceMock_Send_Call{Call: _e.mock.On("Send", ctx, recipients, subject, tpl, content)}
}

func (_c *MailServiceMock_Send_Call) Run(run func(ctx context.Context, recipients []string, subject string, tpl mailer.Template, content interface{})) *MailServiceMock_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string), args[3].(mailer.Template), args[4].(interface{}))
	})
	return _c
}

func (_c *MailServiceMock_Send_Call) Return(_a0 error) *MailServiceMock_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MailServiceMock_Send_Call) RunAndReturn(run func(context.Context, []string, string, mailer.Template, interface{}) error) *MailServiceMock_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailServiceMock creates a new instance of MailServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailServiceMock {
	mock := &MailServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
