// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlite "capuchin/internal/sqlite"
)

// ProjectRepositoryMock is an autogenerated mock type for the ProjectRepository type
type ProjectRepositoryMock struct {
	mock.Mock
}

type ProjectRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectRepositoryMock) EXPECT() *ProjectRepositoryMock_Expecter {
	return &ProjectRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, db, project
func (_m *ProjectRepositoryMock) Create(ctx context.Context, db sqlite.SQLExecutor, project domain.Project) error {
	ret := _m.Called(ctx, db, project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.Project) error); ok {
		r0 = rf(ctx, db, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProjectRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProjectRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - project domain.Project
func (_e *ProjectRepositoryMock_Expecter) Create(ctx interface{}, db interface{}, project interface{}) *ProjectRepositoryMock_Create_Call {
	return &ProjectRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, db, project)}
}

func (_c *ProjectRepositoryMock_Create_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, project domain.Project)) *ProjectRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.Project))
	})
	return _c
}

func (_c *ProjectRepositoryMock_Create_Call) Return(_a0 error) *ProjectRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.Project) error) *ProjectRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID, id
func (_m *ProjectRepositoryMock) FindByID(ctx context.Context, userID string, id string) (domain.Project, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Project, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Project); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProjectRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ProjectRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ProjectRepositoryMock_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *ProjectRepositoryMock_FindByID_Call {
	return &ProjectRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *ProjectRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, userID string, id string)) *ProjectRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProjectRepositoryMock_FindByID_Call) Return(_a0 domain.Project, _a1 error) *ProjectRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProjectRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (domain.Project, error)) *ProjectRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, db, project
func (_m *ProjectRepositoryMock) Update(ctx context.Context, db sqlite.SQLExecutor, project domain.Project) error {
	ret := _m.Called(ctx, db, project)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.Project) error); ok {
		r0 = rf(ctx, db, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProjectRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProjectRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - project domain.Project
func (_e *ProjectRepositoryMock_Expecter) Update(ctx interface{}, db interface{}, project interface{}) *ProjectRepositoryMock_Update_Call {
	return &ProjectRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, db, project)}
}

func (_c *ProjectRepositoryMock_Update_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, project domain.Project)) *ProjectRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.Project))
	})
	return _c
}

func (_c *ProjectRepositoryMock_Update_Call) Return(_a0 error) *ProjectRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.Project) error) *ProjectRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewProjectRepositoryMock creates a new instance of ProjectRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectRepositoryMock {
	mock := &ProjectRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
