// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionRepositoryMock is an autogenerated mock type for the SessionRepository type
type SessionRepositoryMock struct {
	mock.Mock
}

type SessionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepositoryMock) EXPECT() *SessionRepositoryMock_Expecter {
	return &SessionRepositoryMock_Expecter{mock: &_m.Mock}
}

// CancelOld provides a mock function with given fields: ctx, olderThan
func (_m *SessionRepositoryMock) CancelOld(ctx context.Context, olderThan time.Time) error {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for CancelOld")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepositoryMock_CancelOld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOld'
type SessionRepositoryMock_CancelOld_Call struct {
	*mock.Call
}

// CancelOld is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *SessionRepositoryMock_Expecter) CancelOld(ctx interface{}, olderThan interface{}) *SessionRepositoryMock_CancelOld_Call {
	return &SessionRepositoryMock_CancelOld_Call{Call: _e.mock.On("CancelOld", ctx, olderThan)}
}

func (_c *SessionRepositoryMock_CancelOld_Call) Run(run func(ctx context.Context, olderThan time.Time)) *SessionRepositoryMock_CancelOld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *SessionRepositoryMock_CancelOld_Call) Return(_a0 error) *SessionRepositoryMock_CancelOld_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepositoryMock_CancelOld_Call) RunAndReturn(run func(context.Context, time.Time) error) *SessionRepositoryMock_CancelOld_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, session
func (_m *SessionRepositoryMock) Create(ctx context.Context, session domain.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.Session
func (_e *SessionRepositoryMock_Expecter) Create(ctx interface{}, session interface{}) *SessionRepositoryMock_Create_Call {
	return &SessionRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *SessionRepositoryMock_Create_Call) Run(run func(ctx context.Context, session domain.Session)) *SessionRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Session))
	})
	return _c
}

func (_c *SessionRepositoryMock_Create_Call) Return(_a0 error) *SessionRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, domain.Session) error) *SessionRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, userID
func (_m *SessionRepositoryMock) FindAll(ctx context.Context, userID string) ([]domain.Session, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Session, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Session); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepositoryMock_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type SessionRepositoryMock_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionRepositoryMock_Expecter) FindAll(ctx interface{}, userID interface{}) *SessionRepositoryMock_FindAll_Call {
	return &SessionRepositoryMock_FindAll_Call{Call: _e.mock.On("FindAll", ctx, userID)}
}

func (_c *SessionRepositoryMock_FindAll_Call) Run(run func(ctx context.Context, userID string)) *SessionRepositoryMock_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionRepositoryMock_FindAll_Call) Return(_a0 []domain.Session, _a1 error) *SessionRepositoryMock_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepositoryMock_FindAll_Call) RunAndReturn(run func(context.Context, string) ([]domain.Session, error)) *SessionRepositoryMock_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepositoryMock creates a new instance of SessionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepositoryMock {
	mock := &SessionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
