// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlite "capuchin/internal/sqlite"
)

// TimelogRepositoryMock is an autogenerated mock type for the TimelogRepository type
type TimelogRepositoryMock struct {
	mock.Mock
}

type TimelogRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TimelogRepositoryMock) EXPECT() *TimelogRepositoryMock_Expecter {
	return &TimelogRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, db, timelog
func (_m *TimelogRepositoryMock) Create(ctx context.Context, db sqlite.SQLExecutor, timelog domain.Timelog) error {
	ret := _m.Called(ctx, db, timelog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.Timelog) error); ok {
		r0 = rf(ctx, db, timelog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TimelogRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TimelogRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - timelog domain.Timelog
func (_e *TimelogRepositoryMock_Expecter) Create(ctx interface{}, db interface{}, timelog interface{}) *TimelogRepositoryMock_Create_Call {
	return &TimelogRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, db, timelog)}
}

func (_c *TimelogRepositoryMock_Create_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, timelog domain.Timelog)) *TimelogRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.Timelog))
	})
	return _c
}

func (_c *TimelogRepositoryMock_Create_Call) Return(_a0 error) *TimelogRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TimelogRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.Timelog) error) *TimelogRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, db, userID, id
func (_m *TimelogRepositoryMock) Delete(ctx context.Context, db sqlite.SQLExecutor, userID string, id string) error {
	ret := _m.Called(ctx, db, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, string, string) error); ok {
		r0 = rf(ctx, db, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TimelogRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TimelogRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - userID string
//   - id string
func (_e *TimelogRepositoryMock_Expecter) Delete(ctx interface{}, db interface{}, userID interface{}, id interface{}) *TimelogRepositoryMock_Delete_Call {
	return &TimelogRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, db, userID, id)}
}

func (_c *TimelogRepositoryMock_Delete_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, userID string, id string)) *TimelogRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *TimelogRepositoryMock_Delete_Call) Return(_a0 error) *TimelogRepositoryMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TimelogRepositoryMock_Delete_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, string, string) error) *TimelogRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID, id
func (_m *TimelogRepositoryMock) FindByID(ctx context.Context, userID string, id string) (domain.Timelog, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Timelog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Timelog, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Timelog); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Timelog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelogRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type TimelogRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *TimelogRepositoryMock_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *TimelogRepositoryMock_FindByID_Call {
	return &TimelogRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *TimelogRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, userID string, id string)) *TimelogRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TimelogRepositoryMock_FindByID_Call) Return(_a0 domain.Timelog, _a1 error) *TimelogRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelogRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (domain.Timelog, error)) *TimelogRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindLastN provides a mock function with given fields: ctx, userID, n
func (_m *TimelogRepositoryMock) FindLastN(ctx context.Context, userID string, n int) ([]domain.Timelog, error) {
	ret := _m.Called(ctx, userID, n)

	if len(ret) == 0 {
		panic("no return value specified for FindLastN")
	}

	var r0 []domain.Timelog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.Timelog, error)); ok {
		return rf(ctx, userID, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.Timelog); ok {
		r0 = rf(ctx, userID, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Timelog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelogRepositoryMock_FindLastN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLastN'
type TimelogRepositoryMock_FindLastN_Call struct {
	*mock.Call
}

// FindLastN is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - n int
func (_e *TimelogRepositoryMock_Expecter) FindLastN(ctx interface{}, userID interface{}, n interface{}) *TimelogRepositoryMock_FindLastN_Call {
	return &TimelogRepositoryMock_FindLastN_Call{Call: _e.mock.On("FindLastN", ctx, userID, n)}
}

func (_c *TimelogRepositoryMock_FindLastN_Call) Run(run func(ctx context.Context, userID string, n int)) *TimelogRepositoryMock_FindLastN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *TimelogRepositoryMock_FindLastN_Call) Return(_a0 []domain.Timelog, _a1 error) *TimelogRepositoryMock_FindLastN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelogRepositoryMock_FindLastN_Call) RunAndReturn(run func(context.Context, string, int) ([]domain.Timelog, error)) *TimelogRepositoryMock_FindLastN_Call {
	_c.Call.Return(run)
	return _c
}

// FindRunning provides a mock function with given fields: ctx, userID
func (_m *TimelogRepositoryMock) FindRunning(ctx context.Context, userID string) (domain.Timelog, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindRunning")
	}

	var r0 domain.Timelog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Timelog, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Timelog); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.Timelog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelogRepositoryMock_FindRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRunning'
type TimelogRepositoryMock_FindRunning_Call struct {
	*mock.Call
}

// FindRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *TimelogRepositoryMock_Expecter) FindRunning(ctx interface{}, userID interface{}) *TimelogRepositoryMock_FindRunning_Call {
	return &TimelogRepositoryMock_FindRunning_Call{Call: _e.mock.On("FindRunning", ctx, userID)}
}

func (_c *TimelogRepositoryMock_FindRunning_Call) Run(run func(ctx context.Context, userID string)) *TimelogRepositoryMock_FindRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TimelogRepositoryMock_FindRunning_Call) Return(_a0 domain.Timelog, _a1 error) *TimelogRepositoryMock_FindRunning_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelogRepositoryMock_FindRunning_Call) RunAndReturn(run func(context.Context, string) (domain.Timelog, error)) *TimelogRepositoryMock_FindRunning_Call {
	_c.Call.Return(run)
	return _c
}

// TaskReport provides a mock function with given fields: ctx, userID, taskID
func (_m *TimelogRepositoryMock) TaskReport(ctx context.Context, userID string, taskID string) (domain.TaskReport, error) {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for TaskReport")
	}

	var r0 domain.TaskReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.TaskReport, error)); ok {
		return rf(ctx, userID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.TaskReport); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		r0 = ret.Get(0).(domain.TaskReport)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelogRepositoryMock_TaskReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TaskReport'
type TimelogRepositoryMock_TaskReport_Call struct {
	*mock.Call
}

// TaskReport is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskID string
func (_e *TimelogRepositoryMock_Expecter) TaskReport(ctx interface{}, userID interface{}, taskID interface{}) *TimelogRepositoryMock_TaskReport_Call {
	return &TimelogRepositoryMock_TaskReport_Call{Call: _e.mock.On("TaskReport", ctx, userID, taskID)}
}

func (_c *TimelogRepositoryMock_TaskReport_Call) Run(run func(ctx context.Context, userID string, taskID string)) *TimelogRepositoryMock_TaskReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TimelogRepositoryMock_TaskReport_Call) Return(_a0 domain.TaskReport, _a1 error) *TimelogRepositoryMock_TaskReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelogRepositoryMock_TaskReport_Call) RunAndReturn(run func(context.Context, string, string) (domain.TaskReport, error)) *TimelogRepositoryMock_TaskReport_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, db, timelog
func (_m *TimelogRepositoryMock) Update(ctx context.Context, db sqlite.SQLExecutor, timelog domain.Timelog) error {
	ret := _m.Called(ctx, db, timelog)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.Timelog) error); ok {
		r0 = rf(ctx, db, timelog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TimelogRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TimelogRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - timelog domain.Timelog
func (_e *TimelogRepositoryMock_Expecter) Update(ctx interface{}, db interface{}, timelog interface{}) *TimelogRepositoryMock_Update_Call {
	return &TimelogRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, db, timelog)}
}

func (_c *TimelogRepositoryMock_Update_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, timelog domain.Timelog)) *TimelogRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.Timelog))
	})
	return _c
}

func (_c *TimelogRepositoryMock_Update_Call) Return(_a0 error) *TimelogRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TimelogRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.Timelog) error) *TimelogRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTimelogRepositoryMock creates a new instance of TimelogRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimelogRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimelogRepositoryMock {
	mock := &TimelogRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
