// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlite "capuchin/internal/sqlite"
)

// TransactionManagerMock is an autogenerated mock type for the TransactionManager type
type TransactionManagerMock struct {
	mock.Mock
}

type TransactionManagerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionManagerMock) EXPECT() *TransactionManagerMock_Expecter {
	return &TransactionManagerMock_Expecter{mock: &_m.Mock}
}

// ExecuteInTransaction provides a mock function with given fields: ctx, opFuncs
func (_m *TransactionManagerMock) ExecuteInTransaction(ctx context.Context, opFuncs ...func(context.Context, sqlite.SQLExecutor) error) error {
	_va := make([]interface{}, len(opFuncs))
	for _i := range opFuncs {
		_va[_i] = opFuncs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteInTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...func(context.Context, sqlite.SQLExecutor) error) error); ok {
		r0 = rf(ctx, opFuncs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionManagerMock_ExecuteInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteInTransaction'
type TransactionManagerMock_ExecuteInTransaction_Call struct {
	*mock.Call
}

// ExecuteInTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - opFuncs ...func(context.Context , sqlite.SQLExecutor) error
func (_e *TransactionManagerMock_Expecter) ExecuteInTransaction(ctx interface{}, opFuncs ...interface{}) *TransactionManagerMock_ExecuteInTransaction_Call {
	return &TransactionManagerMock_ExecuteInTransaction_Call{Call: _e.mock.On("ExecuteInTransaction",
		append([]interface{}{ctx}, opFuncs...)...)}
}

func (_c *TransactionManagerMock_ExecuteInTransaction_Call) Run(run func(ctx context.Context, opFuncs ...func(context.Context, sqlite.SQLExecutor) error)) *TransactionManagerMock_ExecuteInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(context.Context, sqlite.SQLExecutor) error, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(func(context.Context, sqlite.SQLExecutor) error)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *TransactionManagerMock_ExecuteInTransaction_Call) Return(_a0 error) *TransactionManagerMock_ExecuteInTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionManagerMock_ExecuteInTransaction_Call) RunAndReturn(run func(context.Context, ...func(context.Context, sqlite.SQLExecutor) error) error) *TransactionManagerMock_ExecuteInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionManagerMock creates a new instance of TransactionManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManagerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionManagerMock {
	mock := &TransactionManagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
