// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlite "capuchin/internal/sqlite"

	time "time"
)

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// CancelActivateCode provides a mock function with given fields: ctx, user
func (_m *UserRepositoryMock) CancelActivateCode(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CancelActivateCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryMock_CancelActivateCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelActivateCode'
type UserRepositoryMock_CancelActivateCode_Call struct {
	*mock.Call
}

// CancelActivateCode is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *UserRepositoryMock_Expecter) CancelActivateCode(ctx interface{}, user interface{}) *UserRepositoryMock_CancelActivateCode_Call {
	return &UserRepositoryMock_CancelActivateCode_Call{Call: _e.mock.On("CancelActivateCode", ctx, user)}
}

func (_c *UserRepositoryMock_CancelActivateCode_Call) Run(run func(ctx context.Context, user domain.User)) *UserRepositoryMock_CancelActivateCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *UserRepositoryMock_CancelActivateCode_Call) Return(_a0 error) *UserRepositoryMock_CancelActivateCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_CancelActivateCode_Call) RunAndReturn(run func(context.Context, domain.User) error) *UserRepositoryMock_CancelActivateCode_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, db, user
func (_m *UserRepositoryMock) Create(ctx context.Context, db sqlite.SQLExecutor, user domain.User) error {
	ret := _m.Called(ctx, db, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlite.SQLExecutor, domain.User) error); ok {
		r0 = rf(ctx, db, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - db sqlite.SQLExecutor
//   - user domain.User
func (_e *UserRepositoryMock_Expecter) Create(ctx interface{}, db interface{}, user interface{}) *UserRepositoryMock_Create_Call {
	return &UserRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, db, user)}
}

func (_c *UserRepositoryMock_Create_Call) Run(run func(ctx context.Context, db sqlite.SQLExecutor, user domain.User)) *UserRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlite.SQLExecutor), args[2].(domain.User))
	})
	return _c
}

func (_c *UserRepositoryMock_Create_Call) Return(_a0 error) *UserRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, sqlite.SQLExecutor, domain.User) error) *UserRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNotActivated provides a mock function with given fields: ctx, olderThan
func (_m *UserRepositoryMock) DeleteNotActivated(ctx context.Context, olderThan time.Time) error {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotActivated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryMock_DeleteNotActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotActivated'
type UserRepositoryMock_DeleteNotActivated_Call struct {
	*mock.Call
}

// DeleteNotActivated is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *UserRepositoryMock_Expecter) DeleteNotActivated(ctx interface{}, olderThan interface{}) *UserRepositoryMock_DeleteNotActivated_Call {
	return &UserRepositoryMock_DeleteNotActivated_Call{Call: _e.mock.On("DeleteNotActivated", ctx, olderThan)}
}

func (_c *UserRepositoryMock_DeleteNotActivated_Call) Run(run func(ctx context.Context, olderThan time.Time)) *UserRepositoryMock_DeleteNotActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *UserRepositoryMock_DeleteNotActivated_Call) Return(_a0 error) *UserRepositoryMock_DeleteNotActivated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_DeleteNotActivated_Call) RunAndReturn(run func(context.Context, time.Time) error) *UserRepositoryMock_DeleteNotActivated_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepositoryMock) FindByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type UserRepositoryMock_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepositoryMock_Expecter) FindByEmail(ctx interface{}, email interface{}) *UserRepositoryMock_FindByEmail_Call {
	return &UserRepositoryMock_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *UserRepositoryMock_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepositoryMock_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepositoryMock_FindByEmail_Call) Return(_a0 domain.User, _a1 error) *UserRepositoryMock_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *UserRepositoryMock_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *UserRepositoryMock) FindByID(ctx context.Context, id string) (domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepositoryMock_Expecter) FindByID(ctx interface{}, id interface{}) *UserRepositoryMock_FindByID_Call {
	return &UserRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, id string)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) Return(_a0 domain.User, _a1 error) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
