GET {{api_host}}/settings
Cookie: CAPUCHIN_SID={{session_id}}

###

PUT {{api_host}}/settings
Cookie: CAPUCHIN_SID={{session_id}}
Content-Type: application/json

{
  "dateFormat": "DD.MM.YYYY"
}

###
