// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// SQLExecutorMock is an autogenerated mock type for the SQLExecutor type
type SQLExecutorMock struct {
	mock.Mock
}

type SQLExecutorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SQLExecutorMock) EXPECT() *SQLExecutorMock_Expecter {
	return &SQLExecutorMock_Expecter{mock: &_m.Mock}
}

// NamedExecContext provides a mock function with given fields: ctx, query, arg
func (_m *SQLExecutorMock) NamedExecContext(ctx context.Context, query string, arg interface{}) (sql.Result, error) {
	ret := _m.Called(ctx, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (sql.Result, error)); ok {
		return rf(ctx, query, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) sql.Result); ok {
		r0 = rf(ctx, query, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SQLExecutorMock_NamedExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedExecContext'
type SQLExecutorMock_NamedExecContext_Call struct {
	*mock.Call
}

// NamedExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg interface{}
func (_e *SQLExecutorMock_Expecter) NamedExecContext(ctx interface{}, query interface{}, arg interface{}) *SQLExecutorMock_NamedExecContext_Call {
	return &SQLExecutorMock_NamedExecContext_Call{Call: _e.mock.On("NamedExecContext", ctx, query, arg)}
}

func (_c *SQLExecutorMock_NamedExecContext_Call) Run(run func(ctx context.Context, query string, arg interface{})) *SQLExecutorMock_NamedExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *SQLExecutorMock_NamedExecContext_Call) Return(_a0 sql.Result, _a1 error) *SQLExecutorMock_NamedExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SQLExecutorMock_NamedExecContext_Call) RunAndReturn(run func(context.Context, string, interface{}) (sql.Result, error)) *SQLExecutorMock_NamedExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewSQLExecutorMock creates a new instance of SQLExecutorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSQLExecutorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SQLExecutorMock {
	mock := &SQLExecutorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
