// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionRepoMock is an autogenerated mock type for the SessionRepo type
type SessionRepoMock struct {
	mock.Mock
}

type SessionRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepoMock) EXPECT() *SessionRepoMock_Expecter {
	return &SessionRepoMock_Expecter{mock: &_m.Mock}
}

// UpdateCheckedAt provides a mock function with given fields: ctx, sessionID, checkedAt
func (_m *SessionRepoMock) UpdateCheckedAt(ctx context.Context, sessionID string, checkedAt time.Time) error {
	ret := _m.Called(ctx, sessionID, checkedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCheckedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, sessionID, checkedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepoMock_UpdateCheckedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCheckedAt'
type SessionRepoMock_UpdateCheckedAt_Call struct {
	*mock.Call
}

// UpdateCheckedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - checkedAt time.Time
func (_e *SessionRepoMock_Expecter) UpdateCheckedAt(ctx interface{}, sessionID interface{}, checkedAt interface{}) *SessionRepoMock_UpdateCheckedAt_Call {
	return &SessionRepoMock_UpdateCheckedAt_Call{Call: _e.mock.On("UpdateCheckedAt", ctx, sessionID, checkedAt)}
}

func (_c *SessionRepoMock_UpdateCheckedAt_Call) Run(run func(ctx context.Context, sessionID string, checkedAt time.Time)) *SessionRepoMock_UpdateCheckedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *SessionRepoMock_UpdateCheckedAt_Call) Return(_a0 error) *SessionRepoMock_UpdateCheckedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepoMock_UpdateCheckedAt_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *SessionRepoMock_UpdateCheckedAt_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepoMock creates a new instance of SessionRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepoMock {
	mock := &SessionRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
