// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"
)

// CookieManagerMock is an autogenerated mock type for the CookieManager type
type CookieManagerMock struct {
	mock.Mock
}

type CookieManagerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CookieManagerMock) EXPECT() *CookieManagerMock_Expecter {
	return &CookieManagerMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: c
func (_m *CookieManagerMock) Get(c *fiber.Ctx) string {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CookieManagerMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CookieManagerMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *CookieManagerMock_Expecter) Get(c interface{}) *CookieManagerMock_Get_Call {
	return &CookieManagerMock_Get_Call{Call: _e.mock.On("Get", c)}
}

func (_c *CookieManagerMock_Get_Call) Run(run func(c *fiber.Ctx)) *CookieManagerMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *CookieManagerMock_Get_Call) Return(_a0 string) *CookieManagerMock_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CookieManagerMock_Get_Call) RunAndReturn(run func(*fiber.Ctx) string) *CookieManagerMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewCookieManagerMock creates a new instance of CookieManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCookieManagerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CookieManagerMock {
	mock := &CookieManagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
