// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	zapcore "go.uber.org/zap/zapcore"
)

// LoggerMock is an autogenerated mock type for the Logger type
type LoggerMock struct {
	mock.Mock
}

type LoggerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoggerMock) EXPECT() *LoggerMock_Expecter {
	return &LoggerMock_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with given fields: msg, fields
func (_m *LoggerMock) Error(msg string, fields ...zapcore.Field) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// LoggerMock_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type LoggerMock_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - fields ...zapcore.Field
func (_e *LoggerMock_Expecter) Error(msg interface{}, fields ...interface{}) *LoggerMock_Error_Call {
	return &LoggerMock_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *LoggerMock_Error_Call) Run(run func(msg string, fields ...zapcore.Field)) *LoggerMock_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]zapcore.Field, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(zapcore.Field)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *LoggerMock_Error_Call) Return() *LoggerMock_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Error_Call) RunAndReturn(run func(string, ...zapcore.Field)) *LoggerMock_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function with given fields: msg, fields
func (_m *LoggerMock) Info(msg string, fields ...zapcore.Field) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// LoggerMock_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type LoggerMock_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - fields ...zapcore.Field
func (_e *LoggerMock_Expecter) Info(msg interface{}, fields ...interface{}) *LoggerMock_Info_Call {
	return &LoggerMock_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *LoggerMock_Info_Call) Run(run func(msg string, fields ...zapcore.Field)) *LoggerMock_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]zapcore.Field, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(zapcore.Field)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *LoggerMock_Info_Call) Return() *LoggerMock_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Info_Call) RunAndReturn(run func(string, ...zapcore.Field)) *LoggerMock_Info_Call {
	_c.Run(run)
	return _c
}

// NewLoggerMock creates a new instance of LoggerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerMock {
	mock := &LoggerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
