// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsMock is an autogenerated mock type for the Metrics type
type MetricsMock struct {
	mock.Mock
}

type MetricsMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsMock) EXPECT() *MetricsMock_Expecter {
	return &MetricsMock_Expecter{mock: &_m.Mock}
}

// HTTPRequestDurationSecondsObserve provides a mock function with given fields: method, path, elapsedSeconds
func (_m *MetricsMock) HTTPRequestDurationSecondsObserve(method string, path string, elapsedSeconds float64) {
	_m.Called(method, path, elapsedSeconds)
}

// MetricsMock_HTTPRequestDurationSecondsObserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPRequestDurationSecondsObserve'
type MetricsMock_HTTPRequestDurationSecondsObserve_Call struct {
	*mock.Call
}

// HTTPRequestDurationSecondsObserve is a helper method to define mock.On call
//   - method string
//   - path string
//   - elapsedSeconds float64
func (_e *MetricsMock_Expecter) HTTPRequestDurationSecondsObserve(method interface{}, path interface{}, elapsedSeconds interface{}) *MetricsMock_HTTPRequestDurationSecondsObserve_Call {
	return &MetricsMock_HTTPRequestDurationSecondsObserve_Call{Call: _e.mock.On("HTTPRequestDurationSecondsObserve", method, path, elapsedSeconds)}
}

func (_c *MetricsMock_HTTPRequestDurationSecondsObserve_Call) Run(run func(method string, path string, elapsedSeconds float64)) *MetricsMock_HTTPRequestDurationSecondsObserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(float64))
	})
	return _c
}

func (_c *MetricsMock_HTTPRequestDurationSecondsObserve_Call) Return() *MetricsMock_HTTPRequestDurationSecondsObserve_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsMock_HTTPRequestDurationSecondsObserve_Call) RunAndReturn(run func(string, string, float64)) *MetricsMock_HTTPRequestDurationSecondsObserve_Call {
	_c.Run(run)
	return _c
}

// HTTPRequestsCurrentDec provides a mock function with no fields
func (_m *MetricsMock) HTTPRequestsCurrentDec() {
	_m.Called()
}

// MetricsMock_HTTPRequestsCurrentDec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPRequestsCurrentDec'
type MetricsMock_HTTPRequestsCurrentDec_Call struct {
	*mock.Call
}

// HTTPRequestsCurrentDec is a helper method to define mock.On call
func (_e *MetricsMock_Expecter) HTTPRequestsCurrentDec() *MetricsMock_HTTPRequestsCurrentDec_Call {
	return &MetricsMock_HTTPRequestsCurrentDec_Call{Call: _e.mock.On("HTTPRequestsCurrentDec")}
}

func (_c *MetricsMock_HTTPRequestsCurrentDec_Call) Run(run func()) *MetricsMock_HTTPRequestsCurrentDec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsMock_HTTPRequestsCurrentDec_Call) Return() *MetricsMock_HTTPRequestsCurrentDec_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsMock_HTTPRequestsCurrentDec_Call) RunAndReturn(run func()) *MetricsMock_HTTPRequestsCurrentDec_Call {
	_c.Run(run)
	return _c
}

// HTTPRequestsCurrentInc provides a mock function with no fields
func (_m *MetricsMock) HTTPRequestsCurrentInc() {
	_m.Called()
}

// MetricsMock_HTTPRequestsCurrentInc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPRequestsCurrentInc'
type MetricsMock_HTTPRequestsCurrentInc_Call struct {
	*mock.Call
}

// HTTPRequestsCurrentInc is a helper method to define mock.On call
func (_e *MetricsMock_Expecter) HTTPRequestsCurrentInc() *MetricsMock_HTTPRequestsCurrentInc_Call {
	return &MetricsMock_HTTPRequestsCurrentInc_Call{Call: _e.mock.On("HTTPRequestsCurrentInc")}
}

func (_c *MetricsMock_HTTPRequestsCurrentInc_Call) Run(run func()) *MetricsMock_HTTPRequestsCurrentInc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsMock_HTTPRequestsCurrentInc_Call) Return() *MetricsMock_HTTPRequestsCurrentInc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsMock_HTTPRequestsCurrentInc_Call) RunAndReturn(run func()) *MetricsMock_HTTPRequestsCurrentInc_Call {
	_c.Run(run)
	return _c
}

// HTTPRequestsTotalInc provides a mock function with given fields: method, path, status
func (_m *MetricsMock) HTTPRequestsTotalInc(method string, path string, status string) {
	_m.Called(method, path, status)
}

// MetricsMock_HTTPRequestsTotalInc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPRequestsTotalInc'
type MetricsMock_HTTPRequestsTotalInc_Call struct {
	*mock.Call
}

// HTTPRequestsTotalInc is a helper method to define mock.On call
//   - method string
//   - path string
//   - status string
func (_e *MetricsMock_Expecter) HTTPRequestsTotalInc(method interface{}, path interface{}, status interface{}) *MetricsMock_HTTPRequestsTotalInc_Call {
	return &MetricsMock_HTTPRequestsTotalInc_Call{Call: _e.mock.On("HTTPRequestsTotalInc", method, path, status)}
}

func (_c *MetricsMock_HTTPRequestsTotalInc_Call) Run(run func(method string, path string, status string)) *MetricsMock_HTTPRequestsTotalInc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MetricsMock_HTTPRequestsTotalInc_Call) Return() *MetricsMock_HTTPRequestsTotalInc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsMock_HTTPRequestsTotalInc_Call) RunAndReturn(run func(string, string, string)) *MetricsMock_HTTPRequestsTotalInc_Call {
	_c.Run(run)
	return _c
}

// NewMetricsMock creates a new instance of MetricsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsMock {
	mock := &MetricsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
