// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SessionRepoMock is an autogenerated mock type for the SessionRepo type
type SessionRepoMock struct {
	mock.Mock
}

type SessionRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepoMock) EXPECT() *SessionRepoMock_Expecter {
	return &SessionRepoMock_Expecter{mock: &_m.Mock}
}

// FindByCID provides a mock function with given fields: ctx, cid
func (_m *SessionRepoMock) FindByCID(ctx context.Context, cid string) (domain.Session, error) {
	ret := _m.Called(ctx, cid)

	if len(ret) == 0 {
		panic("no return value specified for FindByCID")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Session, error)); ok {
		return rf(ctx, cid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Session); ok {
		r0 = rf(ctx, cid)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepoMock_FindByCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCID'
type SessionRepoMock_FindByCID_Call struct {
	*mock.Call
}

// FindByCID is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
func (_e *SessionRepoMock_Expecter) FindByCID(ctx interface{}, cid interface{}) *SessionRepoMock_FindByCID_Call {
	return &SessionRepoMock_FindByCID_Call{Call: _e.mock.On("FindByCID", ctx, cid)}
}

func (_c *SessionRepoMock_FindByCID_Call) Run(run func(ctx context.Context, cid string)) *SessionRepoMock_FindByCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionRepoMock_FindByCID_Call) Return(_a0 domain.Session, _a1 error) *SessionRepoMock_FindByCID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepoMock_FindByCID_Call) RunAndReturn(run func(context.Context, string) (domain.Session, error)) *SessionRepoMock_FindByCID_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepoMock creates a new instance of SessionRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepoMock {
	mock := &SessionRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
