// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SessionUpdaterMock is an autogenerated mock type for the SessionUpdater type
type SessionUpdaterMock struct {
	mock.Mock
}

type SessionUpdaterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionUpdaterMock) EXPECT() *SessionUpdaterMock_Expecter {
	return &SessionUpdaterMock_Expecter{mock: &_m.Mock}
}

// UpdateTime provides a mock function with given fields: sessionID
func (_m *SessionUpdaterMock) UpdateTime(sessionID string) {
	_m.Called(sessionID)
}

// SessionUpdaterMock_UpdateTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTime'
type SessionUpdaterMock_UpdateTime_Call struct {
	*mock.Call
}

// UpdateTime is a helper method to define mock.On call
//   - sessionID string
func (_e *SessionUpdaterMock_Expecter) UpdateTime(sessionID interface{}) *SessionUpdaterMock_UpdateTime_Call {
	return &SessionUpdaterMock_UpdateTime_Call{Call: _e.mock.On("UpdateTime", sessionID)}
}

func (_c *SessionUpdaterMock_UpdateTime_Call) Run(run func(sessionID string)) *SessionUpdaterMock_UpdateTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SessionUpdaterMock_UpdateTime_Call) Return() *SessionUpdaterMock_UpdateTime_Call {
	_c.Call.Return()
	return _c
}

func (_c *SessionUpdaterMock_UpdateTime_Call) RunAndReturn(run func(string)) *SessionUpdaterMock_UpdateTime_Call {
	_c.Run(run)
	return _c
}

// NewSessionUpdaterMock creates a new instance of SessionUpdaterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionUpdaterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionUpdaterMock {
	mock := &SessionUpdaterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
