// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "capuchin/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SessionCacheMock is an autogenerated mock type for the SessionCache type
type SessionCacheMock struct {
	mock.Mock
}

type SessionCacheMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionCacheMock) EXPECT() *SessionCacheMock_Expecter {
	return &SessionCacheMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: key, value
func (_m *SessionCacheMock) Add(key string, value domain.Session) bool {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, domain.Session) bool); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SessionCacheMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type SessionCacheMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - key string
//   - value domain.Session
func (_e *SessionCacheMock_Expecter) Add(key interface{}, value interface{}) *SessionCacheMock_Add_Call {
	return &SessionCacheMock_Add_Call{Call: _e.mock.On("Add", key, value)}
}

func (_c *SessionCacheMock_Add_Call) Run(run func(key string, value domain.Session)) *SessionCacheMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.Session))
	})
	return _c
}

func (_c *SessionCacheMock_Add_Call) Return(evicted bool) *SessionCacheMock_Add_Call {
	_c.Call.Return(evicted)
	return _c
}

func (_c *SessionCacheMock_Add_Call) RunAndReturn(run func(string, domain.Session) bool) *SessionCacheMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *SessionCacheMock) Get(key string) (domain.Session, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Session
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (domain.Session, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) domain.Session); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// SessionCacheMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionCacheMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *SessionCacheMock_Expecter) Get(key interface{}) *SessionCacheMock_Get_Call {
	return &SessionCacheMock_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *SessionCacheMock_Get_Call) Run(run func(key string)) *SessionCacheMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SessionCacheMock_Get_Call) Return(value domain.Session, ok bool) *SessionCacheMock_Get_Call {
	_c.Call.Return(value, ok)
	return _c
}

func (_c *SessionCacheMock_Get_Call) RunAndReturn(run func(string) (domain.Session, bool)) *SessionCacheMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionCacheMock creates a new instance of SessionCacheMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionCacheMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionCacheMock {
	mock := &SessionCacheMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
