// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mail "github.com/wneessen/go-mail"

	mock "github.com/stretchr/testify/mock"
)

// MailClientMock is an autogenerated mock type for the MailClient type
type MailClientMock struct {
	mock.Mock
}

type MailClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MailClientMock) EXPECT() *MailClientMock_Expecter {
	return &MailClientMock_Expecter{mock: &_m.Mock}
}

// DialAndSendWithContext provides a mock function with given fields: ctx, messages
func (_m *MailClientMock) DialAndSendWithContext(ctx context.Context, messages ...*mail.Msg) error {
	_va := make([]interface{}, len(messages))
	for _i := range messages {
		_va[_i] = messages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DialAndSendWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*mail.Msg) error); ok {
		r0 = rf(ctx, messages...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MailClientMock_DialAndSendWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialAndSendWithContext'
type MailClientMock_DialAndSendWithContext_Call struct {
	*mock.Call
}

// DialAndSendWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - messages ...*mail.Msg
func (_e *MailClientMock_Expecter) DialAndSendWithContext(ctx interface{}, messages ...interface{}) *MailClientMock_DialAndSendWithContext_Call {
	return &MailClientMock_DialAndSendWithContext_Call{Call: _e.mock.On("DialAndSendWithContext",
		append([]interface{}{ctx}, messages...)...)}
}

func (_c *MailClientMock_DialAndSendWithContext_Call) Run(run func(ctx context.Context, messages ...*mail.Msg)) *MailClientMock_DialAndSendWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*mail.Msg, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(*mail.Msg)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MailClientMock_DialAndSendWithContext_Call) Return(_a0 error) *MailClientMock_DialAndSendWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MailClientMock_DialAndSendWithContext_Call) RunAndReturn(run func(context.Context, ...*mail.Msg) error) *MailClientMock_DialAndSendWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailClientMock creates a new instance of MailClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailClientMock {
	mock := &MailClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
